;rights types

;root - all functions of bot available
;mod - user data editing functions available 
;crypt - crypto data editing functions available
;modcrypt - user crypto data editing functions available 

;you also can give user some rights like 

;{DATA,ECONOMICS,SIMULATION, etc} 

;admins who have rights in all chats
[GLOBAL_ADMINS]
root = 2043848333

